import { ChatRoomItemType } from "@/components/chat/type";

export const allMsg = [
  {
    id: "1",
    roomIdx: 1,
    senderName: "홍길동",
    senderUuid: 2,
    message: "안녕하세요~~",
    createdAt: "2024-03-19T05:26:39.867Z",
  },
  {
    id: "2",
    roomIdx: 1,
    senderName: "김철수",
    senderUuid: 3,
    message: "안녕하세요~~",
    createdAt: "2024-03-19T05:27:39.867Z",
  },
  {
    id: "3",
    roomIdx: 1,
    senderName: "홍길동",
    senderUuid: 2,
    message: "제가 도와드릴게요 ~",
    createdAt: "2024-03-19T05:28:39.867Z",
  },
  {
    id: "4",
    roomIdx: 1,
    senderName: "김철수",
    senderUuid: 3,
    message: "좋아요",
    createdAt: "2024-03-19T05:29:39.867Z",
  },
  {
    id: "5",
    roomIdx: 1,
    senderName: "홍길동",
    senderUuid: 2,
    message: "안녕하세요~~",
    createdAt: "2024-03-19T05:26:39.867Z",
  },
  {
    id: "6",
    roomIdx: 1,
    senderName: "김철수",
    senderUuid: 3,
    message: "안녕하세요~~",
    createdAt: "2024-03-19T05:27:39.867Z",
  },
  {
    id: "7",
    roomIdx: 1,
    senderName: "홍길동",
    senderUuid: 2,
    message:
      "제가 도와드릴게요 ~ aweawdfaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    createdAt: "2024-03-19T05:28:39.867Z",
  },
  {
    id: "8",
    roomIdx: 1,
    senderName: "김철수",
    senderUuid: 3,
    message: "좋아요 asdfssssssssssssssssssssssssssssssss",
    createdAt: "2024-03-19T05:29:39.867Z",
  },
  {
    id: "9",
    roomIdx: 1,
    senderName: "홍길동",
    senderUuid: 2,
    message:
      "제가 도와드릴게요 ~ aweawdfaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    createdAt: "2024-03-19T05:28:39.867Z",
  },
  {
    id: "10",
    roomIdx: 1,
    senderName: "김철수",
    senderUuid: 3,
    message: "좋아요 asdfssssssssssssssssssssssssssssssss",
    createdAt: "2024-03-19T05:29:39.867Z",
  },
];

export const tempList = {
  users: [
    { name: "김철수", userId: "1" },
    { name: "홍철수", userId: "2" },
    { name: "김길동", userId: "3" },
    { name: "홍길동", userId: "4" },
    { name: "김민정", userId: "5" },
    { name: "홍민정", userId: "6" },
    { name: "김민지", userId: "7" },
    { name: "홍민지", userId: "8" },
    { name: "김현지", userId: "9" },
    { name: "홍현지", userId: "10" },
  ],
  price: 30,
  availableBudget: 4000,
  member: 10,
  postId: "",
  transferState: false,
};

// export const tempChatList: ChatRoomItemType[] = [
//   {
//     roomIdx: "1",
//     name: "성당 청소 도와주세요",
//     chatMsg: "제가 도와드릴게요",
//     time: "3분전",
//     transferState: false,
//     msgNum: 0,
//   },
//   {
//     roomIdx: "1",
//     name: "성당 청소 도와주세요",
//     chatMsg: "제가 도와드릴게요",
//     time: "3분전",
//     transferState: false,
//     msgNum: 1,
//   },
//   {
//     roomIdx: "1",
//     name: "성당 청소 도와주세요",
//     chatMsg: "제가 도와드릴게요",
//     time: "3분전",
//     transferState: false,
//     msgNum: 10,
//   },
//   {
//     roomIdx: "1",
//     name: "성당 청소 도와주세요",
//     chatMsg: "제가 도와드릴게요",
//     time: "3분전",
//     transferState: false,
//     msgNum: 100,
//   },
//   {
//     roomIdx: "1",
//     name: "성당 청소 도와주세요",
//     chatMsg: "제가 도와드릴게요",
//     time: "3분전",
//     transferState: false,
//     msgNum: 200,
//   },
//   {
//     roomIdx: "1",
//     name: "성당 청소 도와주세요",
//     chatMsg: "제가 도와드릴게요",
//     time: "3분전",
//     transferState: false,
//     msgNum: 23,
//   },
//   {
//     roomIdx: "1",
//     name: "성당 청소 도와주세요",
//     chatMsg: "제가 도와드릴게요",
//     time: "3분전",
//     transferState: false,
//     msgNum: 0,
//   },
//   {
//     roomIdx: "1",
//     name: "성당 청소 도와주세요",
//     chatMsg: "제가 도와드릴게요",
//     time: "3분전",
//     transferState: false,
//     msgNum: 0,
//   },
//   {
//     roomIdx: "1",
//     name: "성당 청소 도와주세요",
//     chatMsg: "제가 도와드릴게요",
//     time: "3분전",
//     transferState: false,
//     msgNum: 0,
//   },
//   {
//     roomIdx: "1",
//     name: "성당 청소 도와주세요",
//     chatMsg: "제가 도와드릴게요",
//     time: "3분전",
//     transferState: true,
//     msgNum: 0,
//   },
//   {
//     roomIdx: "1",
//     name: "성당 청소 도와주세요",
//     chatMsg: "제가 도와드릴게요",
//     time: "3분전",
//     transferState: true,
//     msgNum: 0,
//   },
// ];
