name: Synchronize to deploy to vercel
on:
  push:
    branches:
      - main
jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Add remote-url and Merge forked-repo changes
        run: |
          git remote add forked-repo https://2-NOW:${{ secrets.TEST_DEPLOY_TOKEN }}@github.com/2-NOW/P.P-client
          git config user.name test
          git config user.email test
          git fetch forked-repo main
          git merge --allow-unrelated-histories -Xours forked-repo/main
          git push forked-repo main
          git remote remove forked-repo
