name: Push to target repository
on:
 push:
   branches:
     - main
jobs:
 push:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout repository
     uses: actions/checkout@v3

   - name: Push to target repository
     run: |
       git config --global user.name "Your Name"
       git config --global user.email "your.email@example.com"
       git remote add target https://x-access-token:${{ secrets.TEST_DEPLOY_TOKEN2 }}@github.com/2-NOW/P.P-client.git
       git push target main
